### ISSUE TITLE
脳死でnpx gatsby new hogeしたら死んだ

### ISSUE THREAD

**Issue by sunakan** [sunakan/notes-about-gatsby#1]
### 環境

Dockerイメージ：node

```
$ node -v
v12.12.0
$ yarn -v
1.19.1
```

### 実行コマンド

```
$ npx gatsby new gatsby-sunabako
```

### 全出力

```
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/8/lib/node_modules/gatsby/node_modules/core-js/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
internal/modules/cjs/loader.js:797
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/8/lib/node_modules/gatsby/node_modules/gatsby-telemetry/src/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
    at Function.Module._load (internal/modules/cjs/loader.js:687:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-telemetry@1.1.35 postinstall: `node src/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-telemetry@1.1.35 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-09T06_34_03_197Z-debug.log
Install for [ 'gatsby@latest' ] failed with code 1
```

**Comment by sunakan** [comment]
バージョン変えてみる -> 駄目だった（エラー文は異なる）

```
$ node -v
v10.17.0
$ yarn -v
1.19.1
```

### 実行コマンド

```
$ npx gatsby new gatsby-sunabako
```

### 全出力

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/16/lib/node_modules/gatsby/node_modules/core-js/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/16/lib/node_modules/gatsby/node_modules/gatsby-telemetry/src/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-telemetry@1.1.35 postinstall: `node src/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-telemetry@1.1.35 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-09T06_48_12_016Z-debug.log
Install for gatsby@latest failed with code 1
```

**Comment by sunakan** [comment]
[公式のリポジトリ（gatsby）](https://github.com/gatsbyjs/gatsby)
のREADMEには

```
$ npm install -g gatsby-cli
```

とあるので試してみる

**Comment by sunakan** [comment]
これだけはうまくいかなくて、Gitがあれば行けた
もともとGitがなかったせいかもしれないので、Gitを入れてから `npx gatsby new gatsby-sunabako` をやってみる

**Comment by sunakan** [comment]
駄目だった

node:v12.12

### 打ったコマンド

```
$ npx gatsby new gatsby-sunabako
```

### 出力結果

```
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/8/lib/node_modules/gatsby/node_modules/core-js/postinstall'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '/root/.npm/_npx/8/lib/node_modules/gatsby/node_modules/gatsby-telemetry/src/postinstall.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gatsby-telemetry@1.1.35 postinstall: `node src/postinstall.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the gatsby-telemetry@1.1.35 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-09T09_28_18_205Z-debug.log
Install for gatsby@latest failed with code 1
```

**Comment by sunakan** [comment]
同じエラー

**Comment by sunakan** [comment]
npxコマンドをやめて gatsby-cliを入れてからgatsbyコマンドでやる（そもそもnpxもよくわかってない）

**Comment by sunakan** [comment]
yarnかnpmを選択する部分があったがとりあえずyarn

速度の違いについてはおいおいでいいする

**Comment by sunakan** [comment]
gatsby-cliを入れてgatsbyコマンドでやれば解決できた
